### ISSUE TITLE
Some websites' icons are not show

### ISSUE THREAD

**Issue by eval-exec** [stefanXO/Tab-Manager-Plus#220]
Tab-Manager-Plus is awesome, thank you.

Recently I found some websites icons are not show, but they have icons actualy:
![image](https://github.com/stefanXO/Tab-Manager-Plus/assets/46400566/c3162ce8-f67f-4aba-ab7d-bb5b556661ce)

How to investigate this issue? What infomation shall I provide to you? Can you reproduce this?

**Comment by mastef** [comment]
I think in this case it's because the github icon is white, and it's not visible on a white background. See if it shows in dark mode?

There were a few favicon fixes in [Chrome 6.0.0](https://github.com/stefanXO/Tab-Manager-Plus/releases/tag/6.0.0), but Github icon is still not visible because it's white on white.
