### ISSUE TITLE
there isn't no more the duplicate tabs search option

### ISSUE THREAD

**Issue by AliasOfiuco** [stefanXO/Tab-Manager-Plus#31]
there isn't no more the duplicate tabs search option

**Comment by smaragdus** [comment]
Yes, the duplicate tabs button has disappeared, screen:

![Tab Manager Plus 5 1 0 - 2019-11-05 - 003](https://user-images.githubusercontent.com/9025757/68169502-1e880d00-ff75-11e9-8e00-eea308c09a44.png)

Making the pop-up window larger did not help.

**Tab Manager Plus** version **5.1.0** (Chromium)

**Comment by mastef** [comment]
Related to #30

That's a bug in 5.1.0 - it's resolved in 5.1.1 and 5.1.2 which is currently pending manual review by the Chrome Webstore team before a release can be published.

You can find a working version until then here : https://github.com/stefanXO/Tab-Manager-Plus/releases

**Comment by smaragdus** [comment]
@mastef 

> That's a bug in 5.1.0 - it's resolved in 5.1.1 and 5.1.2 which is currently pending manual review by the Chrome Webstore team before a release can be published.

I noticed that the [Chromium](https://chrome.google.com/webstore/detail/tab-manager-plus-for-chro/cnkdjjdmfiffagllbiiilooaoofcoeff) version was several releases behind the [Firefox](https://addons.mozilla.org/en-US/firefox/addon/tab-manager-plus-for-firefox/) version and I was wondering why. You explained it but why there need to be a manual review? Have you experienced the same in the past? Yes, I know that I can get version [5.1.3](https://github.com/stefanXO/Tab-Manager-Plus/releases/tag/5.1.3) from [releases](https://github.com/stefanXO/Tab-Manager-Plus/releases) and I will finally do it if the update gets stuck for long in the chrome store.

I think that this issue is not new as some buttons have disappeared in previous releases. Have you considered moving the search box above the tool bar?

**Comment by mastef** [comment]
@smaragdus Every extension update is nowadays flagged for manual review by the Chrome Webstore team. Their policy.

This issue is unrelated to previous issues. It happened due to a new button being added and the width wasn't adjusted to handle that.

**Comment by smaragdus** [comment]
@mastef 

**Tab Manager Plus** was finally updated to version **5.1.2** at Chrome Store but I was surprised to see a huge pop-up window, screen:

![Tab Manager Plus 5 1 2 - 2019-11-06 - 004](https://user-images.githubusercontent.com/9025757/68328222-8eaea400-00d7-11ea-93f7-9cb448f8181e.png)

Is it supposed to be so big?

The values seems to be unchanged:

- **Popup Width - 530**
- **Popup Height - 450**

How can I restore the previous pop-up window size?

**Comment by smaragdus** [comment]
@mastef 

I checked the change log for version [5.1.3](https://github.com/stefanXO/Tab-Manager-Plus/releases/tag/5.1.3) and I suppose that this is the answer to my question:

> - Fix: Popup width adjustable again instead of stuck to 800px

I will have to wait for Chrome Store to finally update to the latest version (**5.1.3**).

**Comment by mastef** [comment]
@smaragdus Yes, that was fixed right after 5.1.2 was submitted and being reviewed. It should be live now on the Chrome Webstore. The current manual review didn't take as long as usual.

Thanks for reporting nevertheless.

**Comment by smaragdus** [comment]
@mastef 

With update to version 5.1.3 everything is back to normal again.

Before submitting new issues/commenting on issues I will check the change log first.

I will start testing the session management feature, if I encounter a problem or if I can think of a possible improvement I will report here.

Thank you for your great work!
